"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Check } from "lucide-react";

export default function Workshops() {
  const [sent, setSent] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setError(""); const form = new FormData(e.currentTarget); const body = Object.fromEntries(form.entries());
    try { const response = await fetch("/api/workshops", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "We couldn't save your request."); setSent(true); }
    catch (err) { setError(err instanceof Error ? err.message : "Please try again."); } finally { setBusy(false); }
  }
  return <main className="checkout-page"><header className="checkout-header"><Link className="brandmark" href="/"><img src="/artini-logo.png" alt="Artini"/></Link><div>GOOD HANDS. GOOD COMPANY.</div><Link href="/#workshops" className="back-link"><ArrowLeft size={14}/> Back to the studio</Link></header><div className="checkout-wrap workshop-request-wrap">{sent ? <section className="checkout-success"><div className="success-icon"><Check size={26}/></div><div className="eyebrow"><span className="eyebrow-line"/> WE'VE GOT YOUR NOTE</div><h1>Let's make<br/><em>something.</em></h1><p>Thanks for reaching out. The studio will be in touch soon to talk through the details and make a plan together.</p><Link href="/" className="button button-dark">Back to the studio <ArrowRight size={16}/></Link></section> : <><div className="checkout-title"><div className="eyebrow"><span className="eyebrow-line"/> A GOOD TIME, BY HAND</div><h1>Let's make<br/><em>room to create.</em></h1><p>Tell us a little about your group and we'll get back to you with ideas.</p></div><form className="workshop-form" onSubmit={submit}><div className="form-grid"><label>I'm interested in<select name="workshop_type" required defaultValue="company"><option value="company">A company team workshop</option><option value="open-studio">An open studio session</option><option value="private-group">A private group gathering</option></select></label><label>Your name<input name="customer_name" required autoComplete="name" placeholder="How should we address you?"/></label><label>Email address<input name="customer_email" required type="email" autoComplete="email" placeholder="you@example.com"/></label><label>Phone number<input name="customer_phone" required type="tel" placeholder="+234 800 000 0000"/></label><label>Company or group name <span className="optional">OPTIONAL</span><input name="organization" placeholder="Who are we creating with?"/></label><label>Number of guests<input name="guest_count" type="number" min="1" max="500" required defaultValue="8"/></label><label>Preferred date <span className="optional">OPTIONAL</span><input name="preferred_date" type="date"/></label><label className="full">Anything else you'd like us to know? <span className="optional">OPTIONAL</span><textarea name="notes" rows={3} placeholder="The occasion, your team, access needs, your ideas…"/></label></div>{error && <p className="form-message" role="alert">{error}</p>}<button className="button button-dark submit-order" disabled={busy}>{busy ? "Sending your note…" : "Tell us about your group"} {!busy && <ArrowRight size={16}/>}</button><p className="secure-note">No payment needed to enquire. We'll follow up personally.</p></form></>}</div><footer className="checkout-footer"><span>ARTINI · LAGOS, NIGERIA</span><Link href="/custom">NEED A HAND? SAY HELLO ↗</Link></footer></main>;
}
