"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, LockKeyhole, Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type CartItem = { id: string; quantity: number; name?: string; price?: number; image_url?: string };
const money = (amount: number) => new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 }).format(amount);
export default function Checkout() {
  const [cart, setCart] = useState<CartItem[]>([]);
  const [email, setEmail] = useState(""); const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [address, setAddress] = useState("");
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [done, setDone] = useState(false); const [signedIn, setSignedIn] = useState(false);
  useEffect(() => { try { setCart(JSON.parse(localStorage.getItem("artini-cart") || "[]")); } catch {} if (process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY) createClient().auth.getUser().then(({ data }) => { if (data.user?.email) { setEmail(data.user.email); setName(data.user.user_metadata?.full_name || ""); setSignedIn(true); } }); }, []);
  const update = (id: string, amount: number) => { const next = cart.map(x => x.id === id ? { ...x, quantity: x.quantity + amount } : x).filter(x => x.quantity > 0); setCart(next); localStorage.setItem("artini-cart", JSON.stringify(next)); };
  const subtotal = cart.reduce((s, x) => s + (x.price || 0) * x.quantity, 0);
  const signIn = async () => { if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY) { setMessage("Set up Supabase to enable Google sign-in."); return; } await createClient().auth.signInWithOAuth({ provider: "google", options: { redirectTo: `${window.location.origin}/auth/callback?next=/checkout` } }); };
  const placeOrder = async (e: React.FormEvent) => { e.preventDefault(); setMessage(""); if (!cart.length) return; setBusy(true); try { let token: string | undefined; if (process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY) { const { data } = await createClient().auth.getSession(); token = data.session?.access_token; }
      const response = await fetch("/api/orders", { method: "POST", headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: JSON.stringify({ customer: { name, email, phone, address }, items: cart.map(({ id, quantity }) => ({ id, quantity })) }) });
      const result = await response.json(); if (!response.ok) throw new Error(result.error || "We couldn't save your order. Please try again.");
      localStorage.removeItem("artini-cart"); setCart([]); setDone(true); setMessage(result.emailSent ? "Mailgun accepted your confirmation email. If it doesn’t arrive, check your spam folder and Mailgun’s delivery logs." : "Your order is saved, but the confirmation email was not sent. Check the dev terminal for the Mailgun status and confirm this checkout address is authorized in the sandbox.");
    } catch (err) { setMessage(err instanceof Error ? err.message : "Something went wrong."); } finally { setBusy(false); } };
  return <main className="checkout-page"><header className="checkout-header"><Link className="brandmark" href="/"><img src="/artini-logo.png" alt="Artini"/></Link><div><LockKeyhole size={14}/> A THOUGHTFUL LITTLE CHECKOUT</div><Link href="/" className="back-link"><ArrowLeft size={14}/> Keep looking</Link></header>
    <div className="checkout-wrap">{done ? <section className="checkout-success"><div className="success-icon"><Check size={26}/></div><div className="eyebrow"><span className="eyebrow-line"/> ORDER RECEIVED</div><h1>Well, this is<br/><em>exciting.</em></h1><p>Your order is safely in our hands. We’ll be in touch with the next steps and a little more about your piece.</p><p className="success-note">{message}</p><Link href="/" className="button button-dark">Back to the studio <ArrowRight size={16}/></Link></section> : <><div className="checkout-title"><div className="eyebrow"><span className="eyebrow-line"/> YOUR NEXT FAVOURITE THING</div><h1>Almost <em>yours.</em></h1><p>We’ll make sure it gets to the right place.</p></div><div className="checkout-columns"><form className="checkout-form" onSubmit={placeOrder}><div className="form-section-head"><span>01</span><h2>Your details</h2>{signedIn && <span className="signed-in">GOOGLE SIGNED IN ✓</span>}</div><div className="form-grid"><label className="full">Full name<input required autoComplete="name" value={name} onChange={e => setName(e.target.value)} placeholder="How should we address you?"/></label><label>Email address<input required type="email" autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Phone number<input required type="tel" autoComplete="tel" value={phone} onChange={e => setPhone(e.target.value)} placeholder="+234 800 000 0000"/></label><label className="full">Delivery address<textarea required autoComplete="street-address" value={address} onChange={e => setAddress(e.target.value)} placeholder="Street, neighbourhood, city" rows={3}/></label></div>{!signedIn && <button type="button" className="google-signin" onClick={signIn}><span className="google-g">G</span> Continue with Google <ArrowRight size={14}/></button>}<div className="form-section-head payment-head"><span>02</span><h2>Payment, personally handled</h2></div><p className="payment-copy">We’ll confirm your order and send payment details by email. Every piece is made with care, so we’ll also confirm your delivery timing with you.</p>{message && <p className="form-message" role="alert">{message}</p>}<button className="button button-dark submit-order" disabled={busy || !cart.length}>{busy ? "Saving your order…" : "Place my order"} {!busy && <ArrowRight size={16}/>}</button><p className="secure-note"><LockKeyhole size={12}/> Your details are only used to look after this order.</p></form>
        <aside className="order-summary"><div className="summary-head"><h2>Your bag</h2><span>{cart.reduce((s,x)=>s+x.quantity,0)} PIECES</span></div>{cart.length ? <div className="summary-items">{cart.map(item => <div className="summary-item" key={item.id}><div className="summary-thumb"><img src={item.image_url || "/art-sun.svg"} alt=""/></div><div className="summary-product"><b>{item.name || item.id}</b><span>{money(item.price || 0)}</span><div className="quantity-control"><button type="button" onClick={() => update(item.id,-1)} aria-label="Decrease quantity">{item.quantity === 1 ? <Trash2 size={12}/> : <Minus size={12}/>}</button><span>{item.quantity}</span><button type="button" onClick={() => update(item.id,1)} aria-label="Increase quantity"><Plus size={12}/></button></div></div><strong>{money((item.price || 0)*item.quantity)}</strong></div>)}</div> : <div className="empty-bag"><ShoppingBag size={25}/><p>Your bag is waiting for a little wonder.</p><Link href="/#collection">Find a piece <ArrowRight size={14}/></Link></div>}<div className="summary-totals"><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Delivery</span><span>Confirmed by email</span></div><div className="total-line"><span>Order total</span><b>{money(subtotal)}</b></div></div><p className="summary-foot">Each piece is made to order with care in Lagos.</p></aside></div></>}</div><footer className="checkout-footer"><span>ARTINI · LAGOS, NIGERIA</span><Link href="/custom">NEED A HAND? SAY HELLO ↗</Link></footer></main>;
}
