"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Check } from "lucide-react";

export default function CustomWork() {
  const [sent, setSent] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setError(""); const body = Object.fromEntries(new FormData(e.currentTarget).entries());
    try { const response = await fetch("/api/custom", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "We couldn't save your note."); setSent(true); }
    catch (err) { setError(err instanceof Error ? err.message : "Please try again."); } finally { setBusy(false); }
  }
  return <main className="checkout-page"><header className="checkout-header"><Link className="brandmark" href="/"><img src="/artini-logo.png" alt="Artini"/></Link><div>YOUR IDEA, OUR THREAD.</div><Link href="/#custom" className="back-link"><ArrowLeft size={14}/> Back to the studio</Link></header><div className="checkout-wrap workshop-request-wrap">{sent ? <section className="checkout-success"><div className="success-icon"><Check size={26}/></div><div className="eyebrow"><span className="eyebrow-line"/> YOUR IDEA IS WITH US</div><h1>Let's make<br/><em>it yours.</em></h1><p>Thank you for sharing your idea. The studio will be in touch soon to dream up a piece that feels like you.</p><Link href="/" className="button button-dark">Back to the studio <ArrowRight size={16}/></Link></section> : <><div className="checkout-title"><div className="eyebrow"><span className="eyebrow-line"/> MADE AROUND YOUR STORY</div><h1>Something<br/><em>just for you.</em></h1><p>Share your idea and we'll be in touch to talk through it together.</p></div><form className="workshop-form" onSubmit={submit}><div className="form-grid"><label>I'm creating for<select name="project_type" required defaultValue="personal"><option value="personal">Myself or someone I love</option><option value="brand">My brand or business</option><option value="space">A home, office or special space</option></select></label><label>Your name<input name="customer_name" required autoComplete="name" placeholder="How should we address you?"/></label><label>Email address<input name="customer_email" required type="email" autoComplete="email" placeholder="you@example.com"/></label><label>Phone number<input name="customer_phone" required type="tel" placeholder="+234 800 000 0000"/></label><label>Brand or organisation <span className="optional">OPTIONAL</span><input name="organization" placeholder="A name, if there is one"/></label><label>When do you need it? <span className="optional">OPTIONAL</span><input name="needed_by" type="date"/></label><label className="full">Tell us the story<textarea name="details" required rows={4} placeholder="The person, place or idea behind your piece…"/></label></div>{error && <p className="form-message" role="alert">{error}</p>}<button className="button button-dark submit-order" disabled={busy}>{busy ? "Sending your note…" : "Share your idea"} {!busy && <ArrowRight size={16}/>}</button><p className="secure-note">No commitment, just a conversation about what we can make.</p></form></>}</div><footer className="checkout-footer"><span>ARTINI · LAGOS, NIGERIA</span><Link href="/custom">NEED A HAND? SAY HELLO ↗</Link></footer></main>;
}
